//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaparkGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunaparkGame.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCESSORIES.
        /// </summary>
        internal static string accessories {
            get {
                return ResourceManager.GetString("accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start advertise.
        /// </summary>
        internal static string advertiseStart {
            get {
                return ResourceManager.GetString("advertiseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        internal static string advertising {
            get {
                return ResourceManager.GetString("advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMUSEMENTS.
        /// </summary>
        internal static string amusementButton {
            get {
                return ResourceManager.GetString("amusementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUILD.
        /// </summary>
        internal static string buildButton {
            get {
                return ResourceManager.GetString("buildButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUY.
        /// </summary>
        internal static string buyButton {
            get {
                return ResourceManager.GetString("buyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity: .
        /// </summary>
        internal static string capacity {
            get {
                return ResourceManager.GetString("capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE COLOR.
        /// </summary>
        internal static string changeColor {
            get {
                return ResourceManager.GetString("changeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contentment:.
        /// </summary>
        internal static string contentment {
            get {
                return ResourceManager.GetString("contentment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        internal static string continueMenu {
            get {
                return ResourceManager.GetString("continueMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crashness: .
        /// </summary>
        internal static string crashness {
            get {
                return ResourceManager.GetString("crashness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current contentment in the park: .
        /// </summary>
        internal static string currentContentment {
            get {
                return ResourceManager.GetString("currentContentment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current count of visitors: .
        /// </summary>
        internal static string currVisitorsCount {
            get {
                return ResourceManager.GetString("currVisitorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demolishing.
        /// </summary>
        internal static string demolishing {
            get {
                return ResourceManager.GetString("demolishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start demolish.
        /// </summary>
        internal static string demolishStart {
            get {
                return ResourceManager.GetString("demolishStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entrance.
        /// </summary>
        internal static string entrainceBuild {
            get {
                return ResourceManager.GetString("entrainceBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance fee: .
        /// </summary>
        internal static string entranceFee {
            get {
                return ResourceManager.GetString("entranceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string exitBuild {
            get {
                return ResourceManager.GetString("exitBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME.
        /// </summary>
        internal static string gameItem {
            get {
                return ResourceManager.GetString("gameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be built an entrance and an exit: .
        /// </summary>
        internal static string hasEntranceExit {
            get {
                return ResourceManager.GetString("hasEntranceExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string helpItem {
            get {
                return ResourceManager.GetString("helpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORIZONTAL.
        /// </summary>
        internal static string horizontalButtonText {
            get {
                return ResourceManager.GetString("horizontalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunger:.
        /// </summary>
        internal static string hunger {
            get {
                return ResourceManager.GetString("hunger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person ID:.
        /// </summary>
        internal static string idPerson {
            get {
                return ResourceManager.GetString("idPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is going to:.
        /// </summary>
        internal static string isGoingToId {
            get {
                return ResourceManager.GetString("isGoingToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string isRunning {
            get {
                return ResourceManager.GetString("isRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string isRunningGate {
            get {
                return ResourceManager.GetString("isRunningGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD THE GAME.
        /// </summary>
        internal static string loadMenu {
            get {
                return ResourceManager.GetString("loadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-term contentment: .
        /// </summary>
        internal static string longtermContentment {
            get {
                return ResourceManager.GetString("longtermContentment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunapark.
        /// </summary>
        internal static string lunaparkUpperBar {
            get {
                return ResourceManager.GetString("lunaparkUpperBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money:.
        /// </summary>
        internal static string moneyCount {
            get {
                return ResourceManager.GetString("moneyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money:.
        /// </summary>
        internal static string moneyPerson {
            get {
                return ResourceManager.GetString("moneyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW GAME.
        /// </summary>
        internal static string newGameMenu {
            get {
                return ResourceManager.GetString("newGameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry.
        /// </summary>
        internal static string noEntry {
            get {
                return ResourceManager.GetString("noEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        internal static string noEntryGate {
            get {
                return ResourceManager.GetString("noEntryGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of service.
        /// </summary>
        internal static string outOfService {
            get {
                return ResourceManager.GetString("outOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string outOfServiceGate {
            get {
                return ResourceManager.GetString("outOfServiceGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATH.
        /// </summary>
        internal static string pathButton {
            get {
                return ResourceManager.GetString("pathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People: .
        /// </summary>
        internal static string peopleCount {
            get {
                return ResourceManager.GetString("peopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prize: .
        /// </summary>
        internal static string prize {
            get {
                return ResourceManager.GetString("prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT.
        /// </summary>
        internal static string quitMenu {
            get {
                return ResourceManager.GetString("quitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair.
        /// </summary>
        internal static string repairButton {
            get {
                return ResourceManager.GetString("repairButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researching.
        /// </summary>
        internal static string researching {
            get {
                return ResourceManager.GetString("researching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start research.
        /// </summary>
        internal static string researchStart {
            get {
                return ResourceManager.GetString("researchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE AS.
        /// </summary>
        internal static string saveAsMenu {
            get {
                return ResourceManager.GetString("saveAsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string saveMenu {
            get {
                return ResourceManager.GetString("saveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: .
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE OF A PLAYING MAP.
        /// </summary>
        internal static string sizeOfMap {
            get {
                return ResourceManager.GetString("sizeOfMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total count of visitors: .
        /// </summary>
        internal static string totalVisitorsCount {
            get {
                return ResourceManager.GetString("totalVisitorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERTICAL.
        /// </summary>
        internal static string verticalButtonText {
            get {
                return ResourceManager.GetString("verticalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        internal static string viewItem {
            get {
                return ResourceManager.GetString("viewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warningMessBox {
            get {
                return ResourceManager.GetString("warningMessBox", resourceCulture);
            }
        }
    }
}
