//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaparkGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunaparkGame.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVERTISE.
        /// </summary>
        internal static string advertiseButton {
            get {
                return ResourceManager.GetString("advertiseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVERTISING.
        /// </summary>
        internal static string advertisingButton {
            get {
                return ResourceManager.GetString("advertisingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMUSEMENTS.
        /// </summary>
        internal static string amusementButton {
            get {
                return ResourceManager.GetString("amusementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        internal static string continueMenu {
            get {
                return ResourceManager.GetString("continueMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMOLISHING.
        /// </summary>
        internal static string demolishingButton {
            get {
                return ResourceManager.GetString("demolishingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMOLISH.
        /// </summary>
        internal static string demolishStartButton {
            get {
                return ResourceManager.GetString("demolishStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BREAK.
        /// </summary>
        internal static string endButton {
            get {
                return ResourceManager.GetString("endButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT.
        /// </summary>
        internal static string endMenu {
            get {
                return ResourceManager.GetString("endMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD THE GAME.
        /// </summary>
        internal static string loadMenu {
            get {
                return ResourceManager.GetString("loadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunapark.
        /// </summary>
        internal static string lunaparkUpperBar {
            get {
                return ResourceManager.GetString("lunaparkUpperBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money:.
        /// </summary>
        internal static string moneyCount {
            get {
                return ResourceManager.GetString("moneyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW GAME.
        /// </summary>
        internal static string newGameMenu {
            get {
                return ResourceManager.GetString("newGameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATH.
        /// </summary>
        internal static string pathButton {
            get {
                return ResourceManager.GetString("pathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People: .
        /// </summary>
        internal static string peopleCount {
            get {
                return ResourceManager.GetString("peopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESEARCHING.
        /// </summary>
        internal static string researchingButton {
            get {
                return ResourceManager.GetString("researchingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START RESEARCH.
        /// </summary>
        internal static string researchStartButton {
            get {
                return ResourceManager.GetString("researchStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE THE GAME.
        /// </summary>
        internal static string saveMenu {
            get {
                return ResourceManager.GetString("saveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE OF A PLAYING MAP.
        /// </summary>
        internal static string sizeOfMap {
            get {
                return ResourceManager.GetString("sizeOfMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
    }
}
